name: Python Formatting ğŸğŸ”

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "py/**"

jobs:
  quality:
    runs-on: ubuntu-latest
          
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Cd into py
      run: cd py

    - name: Set up Python
      run: uv python install
        
    - name: Install dependencies
      run: |
        bash bin/install.sh
        
    - name: Run quality checks
      run: |
        bash bin/fmt.sh --check
